xcodeproj 'Voco/Voco.xcodeproj'
platform :ios, '7.1'
pod 'RestKit',       '~> 0.23.1'
pod 'Reachability',  '~> 3.1.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'TransitionKit', '~> 2.1.0'
pod 'UIAlertView+Blocks', '~> 0.8.1'
pod 'M13Checkbox', '~> 1.1.0'
pod 'ActionSheetPicker2', '~> 0.1'
pod 'US2FormValidator', '~> 1.1.2'
